name: Build & Release EXE (diagnostic)

on:
  push:
    tags: ["v*"]         # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (root)
        run: |
          echo "== LS ROOT =="
          dir
        shell: pwsh

      - name: Fail early if script missing
        run: |
          if (-not (Test-Path "ff_blob_checker_gui.py")) {
            echo "::error ::ff_blob_checker_gui.py not found at repo root."
            dir
            exit 1
          }
        shell: pwsh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          } else {
            pip install pyinstaller
          }
        shell: pwsh

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --clean --onefile ff_blob_checker_gui.py
        shell: pwsh

      - name: List dist artifacts
        run: |
          echo "== LS DIST =="
          if (Test-Path "dist") { dir dist } else { echo "No dist directory found." }
        shell: pwsh

      - name: Rename EXE with version (if present)
        id: rename
        shell: pwsh
        run: |
          $src = "dist/ff_blob_checker_gui.exe"
          if (Test-Path $src) {
            $ver = "${{ github.ref_name }}" -replace '^v',''
            $dst = "dist/ff_blob_checker_gui-$ver-windows-x64.exe"
            Move-Item $src $dst -Force
            echo "artifact=$dst" >> $env:GITHUB_OUTPUT
            echo "version=$ver"  >> $env:GITHUB_OUTPUT
          } else {
            echo "No EXE found to rename."
          }

      - name: Upload build artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

      - name: Create GitHub Release (only if EXE exists)
        if: ${{ steps.rename.outputs.artifact != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "ff_blob_checker_gui ${{ steps.rename.outputs.version }}"
          files: ${{ steps.rename.outputs.artifact }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
